---
# tasks file for postgres
- name: install postgres
  yum:
    name: postgresql-server
    state: latest

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pgdata_dir_version

- name: Ensure PostgreSQL database is initialized.
  command: postgresql-setup initdb -D {{ postgresql_data_dir }}
  when: not pgdata_dir_version.stat.exists
  become: true

- name: enable postgres at boot
  service:
    name: postgresql
    state: started
    enabled: yes

  # only run the next 2 tasks once!
  #  - name: initilize postgres some more
  #    command: chkconfig postgresql on
